FROM fedora:39 AS build
# RUN apk update && apk upgrade
# RUN apk add --no-cache bash git openssh npm python3 py3-pip curl libpq-dev postgresql-client
RUN yum update -y

RUN yum install -y openssl
RUN yum install -y gcc
RUN yum install -y python3
RUN yum install -y python3-pip
RUN yum install -y python3-devel

RUN yum install -y postgresql
RUN yum install -y libpq-devel

RUN yum install -y nodejs
RUN npm install --global prettier
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
WORKDIR /lookup
COPY requirements.txt /lookup/
RUN pip install -r requirements.txt
COPY ./updater.sh /lookup/updater.sh
COPY ./schema.sql /lookup/schema.sql
COPY ./config.json /lookup/config.json
COPY ./lookup /lookup/lookup
CMD ["bash", "updater.sh"]
